This code is used to visualize feature maps from the sprcific layer

In [1]:
from Model import Model
from tensorboardX import SummaryWriter
from torchvision import transforms
import torch
image_path = './example_images/000186.jpg'
from PIL import Image
import cv2
import numpy as np
from torch.autograd import Variable
import torchvision.utils as vutils

In [3]:
net = Model()
net.load_state_dict(torch.load('weights/epoch204densenet.pth'))
net.eval()

DenseNet(
  (features): Sequential(
    (conv0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (norm0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace)
    (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace)
        (conv1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplac

In [4]:
def preprocess_image(cv2im, resize_im=True):
    """
        Processes image for CNNs

    Args:
        PIL_img (PIL_img): Image to process
        resize_im (bool): Resize to 224 or not
    returns:
        im_as_var (Pytorch variable): Variable that contains processed float tensor
    """
    # mean and std list for channels (Imagenet)
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    # Resize image
    if resize_im:
        cv2im = cv2.resize(cv2im, (224, 224))
    im_as_arr = np.float32(cv2im)
    im_as_arr = np.ascontiguousarray(im_as_arr[..., ::-1])
    im_as_arr = im_as_arr.transpose(2, 0, 1)  # Convert array to D,W,H
    # Normalize the channels
    for channel, _ in enumerate(im_as_arr):
        im_as_arr[channel] /= 255
        im_as_arr[channel] -= mean[channel]
        im_as_arr[channel] /= std[channel]
    # Convert to float tensor
    im_as_ten = torch.from_numpy(im_as_arr).float()
    # Add one more channel to the beginning. Tensor shape = 1,3,224,224
    im_as_ten.unsqueeze_(0)
    # Convert to Pytorch variable
    im_as_var = Variable(im_as_ten, requires_grad=True)
    return im_as_var

In [9]:
class FeatureVisualization():
    def __init__(self,img_path,selected_layer):
        self.img_path=img_path
        self.selected_layer=selected_layer
        self.pretrained_model = net.features 
        
    def process_image(self):
        img=cv2.imread(self.img_path)
        img=preprocess_image(img)
        return img

    def get_feature(self):
        # input = Variable(torch.randn(1, 3, 224, 224))
        #writer = SummaryWriter()
        input=self.process_image()
        print(input.shape)
        x=input
        for index,layer in enumerate(self.pretrained_model):
            #print('index',index, layer)
            x=layer(x)
            if (index == self.selected_layer):
                img_grid = vutils.make_grid(x, normalize=True, scale_each=True, nrow=2)  # B，C, H, W
                #writer.add_image('_feature_maps', img_grid, global_step=666)
                return x

    def get_single_feature(self, index):
        features=self.get_feature()
        print('features shape',features.shape)

        feature=features[:,index,:,:]
        print(feature.shape)

        feature=feature.view(feature.shape[1],feature.shape[2])
        print(feature.shape)

        return feature

    def save_feature_to_img(self):
        #to numpy
        for i in range(1024):
            feature=self.get_single_feature(i)
            feature=feature.data.numpy()
        
            #use sigmod to [0,1]
            feature= 1.0/(1+np.exp(-1*feature))

            # to [0,255]
            feature=np.round(feature*255)
            print(feature[0])
            feature = cv2.resize(feature, (256,256))
            feature = feature.astype(np.uint8)
            #feature = cv2.applyColorMap(feature, cv2.COLORMAP_AUTUMN)

            cv2.imwrite('./feature/8/img_%d.jpg'%(i), feature)


In [11]:
if __name__=='__main__':
    # get class
    myClass=FeatureVisualization(image_path,8)
    print (myClass.pretrained_model)

    myClass.save_feature_to_img()

Sequential(
  (conv0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (norm0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu0): ReLU(inplace)
  (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (denseblock1): _DenseBlock(
    (denselayer1): _DenseLayer(
      (norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu1): ReLU(inplace)
      (conv1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu2): ReLU(inplace)
      (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    )
    (denselayer2): _DenseLayer(
      (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu1): ReLU(inplace)
      (conv1): Conv2d(96, 128, kernel_size=(1, 1), st

features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[147. 132. 131. 131. 129. 130. 131. 129. 131. 131. 130. 130. 133. 140.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 129. 128. 128. 130. 131. 129. 129. 127. 130. 125. 127. 131. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[122. 125. 123. 126. 126. 129. 128. 128. 128. 125. 129. 125. 128. 122.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[134. 132. 135. 136. 135. 135. 133. 137. 135. 136. 134. 135. 135. 134.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 136. 135. 136. 137. 137. 137. 138. 139. 134. 134. 141. 134. 139.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[126. 138. 137. 134. 133. 134. 129. 127. 131. 129. 133. 135. 132. 125.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[120. 123. 121. 120. 120. 122. 123. 122. 121. 124. 125. 121. 120. 125.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[158. 140. 140. 144. 141. 145. 144. 146. 143. 147. 145. 144. 147. 157.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[145. 137. 140. 141. 137. 135. 136. 136. 139. 138. 135. 138. 140. 145.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[143. 131. 131. 134. 134. 133. 132. 134. 135. 131. 135. 137. 133. 138.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 132. 132. 131. 132. 133. 131. 134. 132. 128. 129. 131. 133. 128.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[121. 123. 124. 122. 122. 122. 122. 124. 124. 123. 124. 123. 120. 126.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[130. 131. 134. 133. 133. 131. 133. 134. 134. 132. 130. 134. 132. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[141. 136. 139. 137. 133. 134. 134. 136. 136. 136. 133. 136. 137. 146.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[147. 138. 140. 137. 137. 141. 140. 141. 140. 139. 140. 144. 140. 144.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[143. 139. 142. 141. 140. 145. 141. 140. 140. 143. 140. 142. 143. 146.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[126. 125. 126. 124. 126. 127. 125. 125. 123. 125. 127. 125. 122. 123.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[134. 123. 123. 124. 125. 127. 124. 120. 120. 123. 122. 121. 123. 131.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[135. 128. 129. 127. 123. 126. 126. 122. 126. 128. 125. 126. 125. 129.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[140. 129. 131. 131. 130. 126. 129. 126. 130. 127. 128. 130. 129. 134.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[115. 124. 123. 123. 119. 121. 124. 121. 120. 120. 120. 122. 120. 119.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[138. 131. 134. 137. 134. 132. 134. 136. 135. 134. 131. 132. 132. 139.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[121. 129. 130. 131. 131. 127. 129. 127. 129. 128. 128. 128. 127. 124.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[139. 132. 134. 133. 132. 131. 132. 132. 132. 131. 131. 130. 133. 139.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 127. 127. 128. 128. 130. 127. 125. 128. 128. 126. 129. 127. 123.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[140. 134. 132. 136. 134. 133. 134. 136. 137. 132. 136. 136. 139. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[144. 130. 131. 133. 133. 128. 133. 133. 134. 130. 131. 134. 132. 140.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[133. 136. 131. 133. 133. 132. 131. 132. 132. 129. 130. 131. 132. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[115. 118. 117. 115. 115. 116. 114. 114. 111. 111. 114. 113. 112. 116.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[132. 133. 135. 134. 130. 133. 132. 135. 131. 129. 133. 132. 134. 128.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[122. 121. 120. 124. 127. 130. 133. 133. 132. 132. 133. 132. 132. 125.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[116. 116. 123. 121. 120. 118. 116. 115. 116. 117. 118. 118. 111. 109.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[109. 118. 109. 109. 110. 111. 110. 106. 112. 109. 111. 111. 119. 107.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[122. 118. 126. 125. 121. 118. 117. 118. 117. 115. 114. 116. 111. 121.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[126. 106. 114. 114. 114. 111. 112. 112. 110. 112. 113. 111. 106. 122.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[126. 130. 136. 136. 135. 133. 137. 136. 130. 134. 139. 136. 140. 116.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 123. 125. 122. 121. 123. 124. 124. 122. 123. 123. 124. 121. 122.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 128. 126. 128. 129. 130. 130. 130. 130. 129. 129. 132. 136. 132.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 134. 129. 125. 129. 129. 128. 127. 129. 128. 126. 127. 127. 127.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[114. 106. 107. 110. 115. 120. 123. 123. 122. 123. 121. 122. 118. 120.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[216. 181. 153. 160. 161. 162. 162. 160. 161. 164. 163. 166. 192. 220.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[134. 135. 139. 138. 139. 137. 134. 134. 135. 135. 134. 135. 133. 136.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[179. 159. 156. 158. 156. 153. 151. 147. 146. 148. 146. 145. 159. 183.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[ 97. 103. 104. 109. 112. 114. 117. 116. 113. 115. 116. 114. 113.  94.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[ 62.  88. 107.  96.  95.  95.  91.  93.  98.  93.  94. 101.  75.  62.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[ 91.  97. 103. 102. 101. 102. 105. 106. 108. 110. 108. 104.  97.  89.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[133. 112. 123. 132. 130. 129. 128. 129. 129. 129. 126. 121. 119. 133.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[125. 116. 116. 115. 116. 119. 121. 122. 121. 121. 121. 125. 133. 121.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[115. 121. 120. 118. 118. 119. 119. 119. 120. 119. 118. 117. 121. 109.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[111. 122. 123. 124. 128. 128. 129. 128. 129. 130. 126. 124. 118. 116.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[ 95. 101. 103. 107. 108. 109. 110. 111. 110. 110. 107. 105. 100.  85.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[132. 124. 127. 127. 126. 129. 133. 132. 134. 134. 129. 134. 155. 108.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[108. 123. 124. 126. 123. 120. 119. 117. 114. 111. 109. 103.  95. 101.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[112. 104. 109. 114. 114. 118. 118. 121. 121. 120. 115. 114.  92. 109.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[115. 110. 123. 118. 115. 119. 119. 120. 121. 118. 118. 124. 115. 113.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[135. 135. 126. 126. 127. 126. 129. 128. 129. 130. 133. 128. 131. 130.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[ 95.  96. 107. 108. 105. 103. 102. 103. 103. 102. 102.  98.  96.  81.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[117. 115. 124. 125. 120. 117. 117. 117. 117. 115. 115. 108.  92. 102.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[142. 155. 145. 135. 137. 141. 140. 140. 142. 141. 139. 147. 163. 139.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[165. 166. 160. 160. 157. 152. 151. 151. 152. 150. 151. 153. 164. 163.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 123. 130. 133. 133. 132. 132. 133. 133. 133. 131. 130. 124. 135.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[138. 120. 120. 119. 120. 120. 118. 116. 115. 116. 114. 113. 108. 138.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[109. 134. 129. 125. 127. 128. 128. 130. 128. 123. 125. 125.  88. 102.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[138.  98. 103. 112. 111. 112. 111. 107. 108. 108. 105. 100.  98. 121.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[133. 115. 127. 127. 131. 134. 135. 133. 135. 137. 134. 128. 116. 133.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[139. 119. 120. 119. 121. 122. 123. 125. 125. 125. 125. 130. 121. 138.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[132. 104. 105. 120. 120. 116. 117. 118. 117. 116. 111. 111.  89. 109.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[111. 126. 132. 121. 120. 122. 123. 125. 122. 117. 117. 128. 112. 109.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[139. 103. 115. 117. 120. 120. 122. 123. 126. 129. 124. 119. 105. 134.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[125. 122. 117. 114. 118. 119. 116. 114. 114. 111. 108. 115. 120. 115.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 103. 117. 124. 119. 116. 118. 120. 121. 121. 121. 119. 104. 125.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[125. 143. 128. 129. 131. 131. 130. 129. 129. 127. 131. 128. 130. 122.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[123. 139. 129. 127. 129. 130. 128. 128. 128. 128. 130. 130. 142. 117.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[151. 143. 132. 139. 136. 136. 136. 135. 133. 134. 136. 140. 159. 148.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[145. 107. 138. 138. 119. 131. 143. 136. 134. 139. 133. 132. 136. 128.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[117. 129. 123. 121. 125. 129. 127. 124. 129. 128. 126. 126. 128. 119.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 120. 123. 124. 119. 117. 118. 121. 120. 123. 122. 123. 117. 143.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 104. 115. 121. 114. 112. 116. 116. 113. 114. 114. 110. 106. 129.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[140. 157. 143. 138. 141. 147. 144. 142. 142. 143. 141. 140. 163. 135.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[142. 115. 128. 124. 126. 130. 128. 125. 127. 128. 127. 132. 100. 154.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[132. 108. 121. 121. 120. 119. 122. 121. 122. 122. 120. 124. 103. 131.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[131.  86. 104. 105. 107. 111. 111. 109. 110. 112. 111. 116.  80. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[152. 117. 128. 127. 125. 124. 124. 124. 123. 121. 117. 120. 125. 150.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 123. 127. 126. 127. 129. 127. 126. 125. 127. 127. 126. 126. 138.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[142. 122. 129. 134. 132. 132. 132. 133. 134. 132. 130. 130. 126. 145.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[120. 112. 120. 120. 121. 120. 120. 119. 121. 122. 122. 124. 111. 118.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[151. 162. 145. 144. 145. 144. 144. 145. 146. 144. 147. 149. 175. 165.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[137. 124. 121. 124. 123. 124. 123. 124. 124. 123. 124. 124. 116. 137.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 120. 127. 125. 123. 124. 124. 124. 124. 124. 125. 123. 119. 126.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[135. 124. 129. 128. 131. 130. 129. 128. 128. 130. 130. 132. 126. 127.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[120.  92. 104. 107. 107. 108. 110. 113. 111. 110. 103.  95.  75. 117.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[109.  89. 100. 102. 100.  96. 100. 102. 100.  97.  93.  89.  81. 106.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[172. 146. 152. 152. 154. 153. 153. 152. 152. 155. 154. 156. 147. 175.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[151. 124. 124. 129. 128. 124. 125. 126. 125. 128. 126. 127. 120. 138.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[149. 162. 137. 141. 143. 143. 140. 138. 139. 140. 139. 140. 157. 145.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[168. 127. 134. 134. 135. 133. 134. 134. 135. 135. 132. 136. 132. 172.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[152. 135. 129. 133. 133. 134. 134. 134. 134. 134. 132. 134. 124. 153.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[172. 119. 126. 126. 125. 122. 120. 118. 117. 119. 118. 122. 102. 161.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[187. 143. 142. 150. 153. 150. 150. 149. 148. 148. 146. 147. 143. 190.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[144.  91.  97. 101. 104. 106. 106. 104. 106. 107. 105. 100.  96. 141.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[144. 118. 118. 119. 121. 122. 121. 122. 121. 121. 119. 121. 120. 146.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[123. 113. 112. 116. 119. 120. 121. 120. 120. 121. 121. 118. 111. 126.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[127. 132. 136. 134. 136. 135. 134. 133. 135. 136. 137. 141. 136. 134.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[119. 106. 123. 120. 118. 118. 120. 123. 123. 122. 119. 119.  88. 123.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[146. 119. 120. 122. 123. 123. 123. 123. 122. 122. 120. 119. 121. 144.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[180. 127. 135. 135. 137. 134. 134. 132. 132. 137. 134. 137. 121. 179.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[150. 116. 122. 125. 125. 125. 125. 126. 126. 128. 126. 118. 109. 149.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[179.  94. 115. 117. 119. 117. 119. 118. 117. 119. 115. 117.  90. 169.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[183.  99. 126. 130. 131. 131. 135. 135. 133. 134. 130. 130. 110. 193.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[210. 110. 131. 128. 129. 124. 127. 127. 127. 132. 126. 130. 106. 214.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[175. 106. 124. 124. 127. 126. 126. 126. 124. 127. 125. 127. 105. 180.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[121. 121. 116. 113. 114. 115. 116. 117. 117. 117. 115. 113. 122. 118.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[148. 114. 129. 129. 129. 126. 126. 125. 124. 124. 122. 126. 115. 151.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[167. 142. 135. 139. 139. 141. 141. 142. 142. 142. 142. 143. 155. 169.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[150. 116. 122. 124. 124. 124. 125. 123. 122. 124. 124. 125. 104. 153.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])


features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[142. 126. 129. 132. 132. 131. 129. 129. 130. 131. 132. 137. 148. 139.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[169. 124. 127. 130. 132. 131. 132. 132. 131. 134. 130. 129. 121. 168.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[190. 126. 136. 138. 140. 139. 140. 139. 141. 148. 146. 151. 141. 193.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[151. 113. 121. 125. 125. 125. 124. 124. 123. 123. 119. 117. 107. 147.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
torch.Size([1, 14, 14])
torch.Size([14, 14])
[187. 121. 132. 133. 134. 131. 133. 130. 129. 131. 128. 135. 123. 190.]
torch.Size([1, 3, 224, 224])
features shape torch.Size([1, 1024, 14, 14])
